name: ERA5_interactive
channels:
  - conda-forge
dependencies:
  - jupyterlab
  - jupyterlab-myst
  - jupyter_server
  - zarr
  - dask
  - xarray
  - intake=2.0.8
  - intake-esm=2024.2.6
  - geoviews
  - datashader
  - matplotlib
  - panel
  - pandas
  - requests
  - pathlib
  - metpy
  - scipy
  - geopandas
  - gcsfs
  - cf_xarray
  - hvplot
  - spatialpandas
  - watchfiles
  - mystmd
